<?php
/**
 * @file
 * Media Hub module hooks.
 */

/**
 * Implements hook_theme().
 */
function media_hub_theme(): array {
  return [
    'page__media_hub' => [
      'base hook' => 'page',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function media_hub_theme_suggestions_alter(array &$suggestions, array $variables, string $hook): void {
  if ($hook === 'page' && \Drupal::routeMatch()->getRouteName() === 'view.media_center.page_1') {
    $suggestions[] = 'page__media_hub';
  }
}

/**
 * Implements hook_page_attachments().
 */
function media_hub_page_attachments(array &$attachments): void {
  $route = \Drupal::routeMatch()->getRouteName();
  if ($route === 'view.media_center.page_1') {
    $attachments['#attached']['library'][] = 'media_hub/media_hub_app';
  }
}
